version: "3.6"

services:

  backend:
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=mysql://root:verysecretpass@database:3306/sequra_challenge?serverVersion=mariadb-10.5.13
      - APP_ENV=dev
      - MONGO_DB_USER=
      - MONGO_DB_PASSWORD=
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=sequra
    networks:
      - sequra

#  mongo:
#    ports:
#      - "27017:27017"
##    environment:
##      MONGO_INITDB_ROOT_USERNAME: root
##      MONGO_INITDB_ROOT_PASSWORD: verysecretpass
#    networks:
#      - sequra
#
#  mongo-express:
#      ports:
#        - "8888:8081"
#      networks:
#        - sequra

  database:
    ports:
      - "3306:3306"
    networks:
      - sequra


networks:
  sequra: