version: "3.6"

services:

  backend:
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=mysql://root:verysecretpass@database:3306/sequra?serverVersion=mariadb-10.5.13
      - MONGO_DB_USER=
      - MONGO_DB_PASSWORD=
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=sequra
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - sequra

  rabbitmq:
    networks:
      - sequra

  database:
    ports:
      - "3306:3306"
    networks:
      - sequra


networks:
  sequra: