doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            disbursement_reference: App\SequraChallenge\Disbursements\Infrastructure\Persistence\Doctrine\DisbursementReferenceType
            merchant_reference: App\SequraChallenge\Merchants\Infrastructure\Persistence\Doctrine\MerchantReferenceType
            disbursement_line_id: App\SequraChallenge\DisbursementLines\Infrastructure\Persistence\Doctrine\DisbursementLineIdType
            merchant_monthly_fee_id: App\SequraChallenge\MerchantMonthlyFees\Infrastructure\Persistence\Doctrine\MerchantMonthlyFeeIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\SequraChallenge\Merchants:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/SequraChallenge/Merchants/Infrastructure/Persistence/Doctrine'
                prefix: 'App\SequraChallenge\Merchants\Domain\Entity'
                alias: App\SequraChallenge\Merchants
            App\SequraChallenge\Dibursements:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/SequraChallenge/Disbursements/Infrastructure/Persistence/Doctrine'
                prefix: 'App\SequraChallenge\Disbursements\Domain\Entity'
                alias: App\SequraChallenge\Disbursements
            App\SequraChallenge\DibursementLines:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/SequraChallenge/DisbursementLines/Infrastructure/Persistence/Doctrine'
                prefix: 'App\SequraChallenge\DisbursementLines\Domain\Entity'
                alias: App\SequraChallenge\DisbursementLines
            App\SequraChallenge\MerchantMonthlyFees:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/SequraChallenge/MerchantMonthlyFees/Infrastructure/Persistence/Doctrine'
                prefix: 'App\SequraChallenge\MerchantMonthlyFees\Domain\Entity'
                alias: App\SequraChallenge\MerchantMonthlyFees

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
