framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(RABBITMQ_URL)%'
            # sync: 'sync://'
            async:
                dsn: '%env(RABBITMQ_URL)%'
            purchase_created:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: purchase_created
                        type: direct
                        arguments: { }
                    queues:
                        disbursement.find_or_create_on_purchase_created:
                            arguments: { }
            disbursement_calculated:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: disbursement_calculated
                        type: direct
                        arguments: { }
                    queues:
                        disbursement_line.create_on_disbursement_calculated:
                            arguments: { }
            disbursement_line_created:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: disbursement_line_created
                        type: direct
                        arguments: { }
                    queues:
                        disbursement.update_amount_and_fee_on_disbursement_line_created:
                            arguments: { }
            disbursement_amount_and_fee_increased:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: disbursement_amount_and_fee_increased
                        type: direct
                        arguments: { }
                    queues:
                        merchant_monthly_fee.update_amount_and_fee_on_disbursement_amount_and_fee_increased:
                            arguments: { }

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            #'App\Shared\Domain\Bus\Event\DomainEvent': async
            'App\SequraChallenge\Purchases\Domain\Events\PurchaseCreatedEvent': purchase_created
            'App\SequraChallenge\Disbursements\Domain\Events\DisbursementCalculatedEvent': disbursement_calculated
            'App\SequraChallenge\DisbursementLines\Domain\Events\DisbursementLineCreatedEvent': disbursement_line_created
            'App\SequraChallenge\Disbursements\Domain\Events\DisbursementAmountAndFeeIncreasedEvent': disbursement_amount_and_fee_increased
            'App\Shared\Domain\Bus\Command\Command': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
                sync: 'sync://'

            routing:
                # Route your messages to the transports
                # 'App\Message\YourMessage': async
                'App\SequraChallenge\Purchases\Domain\Events\PurchaseCreatedEvent': sync
                'App\SequraChallenge\Disbursements\Domain\Events\DisbursementCalculatedEvent': sync
                'App\SequraChallenge\DisbursementLines\Domain\Events\DisbursementLineCreatedEvent': sync
                'App\SequraChallenge\Disbursements\Domain\Events\DisbursementAmountAndFeeIncreasedEvent': sync
                'App\Shared\Domain\Bus\Command\Command': sync
